[project]
name = "irlab-ctl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "influxdb-client>=1.49.0",
    "pysnmp>=7.1.22",
    "slack-sdk>=3.39.0",
]

[project.scripts]
irlab-ctl = "irlab_ctl:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
